#!/bin/sh
#we might run inside busybox ash, no bash syntax

DEPLOY_DIR=${DEPLOY_DIR-/opt/openshift}
if [ -n "$JBOSS_HOME" ]; then
	DEPLOY_DIR=$JBOSS_HOME/standalone/deployments
else if [ -n "$JWS_HOME" ]; then
	DEPLOY_DIR=$JWS_HOME/webapps
fi


echo " Axa - Custom code for binary deployment"
# Picks up WAR_FILE_URL from buildConfig
if[ -n "$WAR_FILE_URL" ]; then
  	EXTENSION=$(".${WAR_FILE_URL##*.})
  	echo "url: ${WAR_FILE_URL} ext: $EXTENSION"
  	curl -o ${DEPLOY_DIR}/ROOT${EXTENSION} -O ${WAR_FILE_URL}
fi
