#!/bin/sh

DEPLOY_DIR=${DEPLOY_DIR-/opt/openshift}

# the subdirectory within LOCAL_SOURCE_DIR from where we should copy build artifacts
ARTIFACT_DIR=${ARTIFACT_DIR-target}

function copy_artifacts() {
  if [ -d $1 ]; then
    echo "Copying all [JWE]AR artifacts from $1 directory into $DEPLOY_DIR for later deployment..."
    cp -v $1/*.?ar $DEPLOY_DIR 2> /dev/null
  fi
}


# Copy (probably binary) artifacts from the deployments/
# directory to the $DEPLOY_DIR directory for later deployment
copy_artifacts "deployments"

  echo " Axa - Custom code for binary deployment"
# Picks up WAR_FILE_URL from buildConfig
if[ ! -z $WAR_FILE_URL ]; then
  	EXTENSION=$([[ "$WAR_FILE_URL" = *.* ]] && echo ".${WAR_FILE_URL##*.}" || echo '').
  	echo "${WAR_FILE_URL} $EXTENSION"
  	curl -o ${DEPLOY_DIR}/ROOT${EXTENSION} -O ${WAR_FILE_URL}
fi
